spring:
  application:
    name: itoken-config
  boot:
    admin:
      client:
        url: http://192.168.241.133:8084
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/iitoken/itoken-config.git
          search-paths: respo
          username: hbsun888
          password: sunhaibo888
  zipkin:
    base-url: http://192.168.241.133:9411

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.241.133:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info